<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);AVLN3001</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <ClassIslandPluginSdkVersion>2.1.0.1</ClassIslandPluginSdkVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="$(ClassIslandPluginSdkVersion)">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\quotes.jsonc">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
